import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getHomePage } from "./lib/home-page";

export async function getStaticProps() {
  let postData = await getHomePage();
  console.log(postData);
  return {
    props: { postData },
  };
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <p>footer</p>
      </footer>
    </div>
  );
}
